[package]
name = "playdate-sdk-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
flate2 = "1.1.1"
reqwest = { version = "0.12", features = ["json"] }
tar = "0.4.44"
tokio = { version = "1", features = ["full"] }
